apiVersion: apps/v1
kind: Deployment
metadata:
  name: llm-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: llm-api
  template:
    metadata:
      labels:
        app: llm-api
    spec:
      containers:
      - name: llm-api
        image: docker.io/library/llm-api:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8000
        env:
        - name: OLLAMA_HOST
          value: "http://192.168.65.37:11434"
