FROM python:3.12-slim

WORKDIR /app

RUN pip install mlflow scikit-learn pandas flask gunicorn

COPY mlruns/ /app/mlruns/

ENV MLFLOW_ALLOW_FILE_STORE=true

EXPOSE 8080

COPY serve.py /app/serve.py

ENTRYPOINT ["python", "serve.py"]
CMD ["serve"]
