apiVersion: apps/v1
kind: Deployment
metadata:
  name: iris-model
spec:
  replicas: {{ .Values.irisModel.replicas }}
  selector:
    matchLabels:
      app: iris-model
  template:
    metadata:
      labels:
        app: iris-model
    spec:
      containers:
      - name: iris-model
        image: {{ .Values.irisModel.image }}
        imagePullPolicy: Never
        ports:
        - containerPort: {{ .Values.irisModel.port }}
