name: MLOps Pipeline

on:
  push:
    branches: [ main ]

jobs:
  train-and-build:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        source ~/mlops-project/mlops-env/bin/activate
        pip install mlflow scikit-learn pandas

    - name: Train model
      run: |
        source ~/mlops-project/mlops-env/bin/activate
        cd $GITHUB_WORKSPACE
        MLFLOW_ALLOW_FILE_STORE=true python train.py

    - name: Build Docker image
      run: |
        docker build -t sambasy/iris-model:latest .

    - name: Push Docker image
      run: |
        echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
        docker push sambasy/iris-model:latest

    - name: Deploy sur Kubernetes
      run: |
        kubectl apply -f deployment.yml
        kubectl apply -f service.yml
        kubectl rollout restart deployment/iris-model
