name: MLOps Pipeline

on:
  push:
    branches: [ main ]
    paths:
      - 'train.py'
      - 'Dockerfile.sagemaker'
      - 'serve.py'
      - 'llm_app.py'
      - 'Dockerfile.llm'
      - 'mlops-chart/**'
      - 'terraform/**'
      - '.github/workflows/mlops-pipeline.yml'

jobs:
  # ── JOB 1 : Train + Deploy Local K8s ──
  iris-pipeline:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        source ~/mlops-project/mlops-env/bin/activate
        pip install mlflow scikit-learn pandas

    - name: Train model
      run: |
        source ~/mlops-project/mlops-env/bin/activate
        cd $GITHUB_WORKSPACE
        MLFLOW_TRACKING_URI=http://192.168.65.44:5000 \
        MLFLOW_ALLOW_FILE_STORE=true \
        python train.py

    - name: Copier mlruns dans workspace
      run: |
        cp -r ~/mlops-project/mlruns $GITHUB_WORKSPACE/mlruns

    - name: Build and Push vers Docker Hub
      run: |
        docker build -t sambasy/iris-model:latest .
        echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
        docker push sambasy/iris-model:latest

    - name: Deploy sur K8s local
      run: |
        helm upgrade --install mlops-app ./mlops-chart \
          --set irisModel.image=sambasy/iris-model:latest \
          --set llmApi.image=sambasy/llm-api:latest

  # ── JOB 2 : LLM Pipeline ──
  llm-pipeline:
    runs-on: self-hosted
    needs: iris-pipeline

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Build LLM image
      run: |
        docker build -f Dockerfile.llm -t sambasy/llm-api:latest .

    - name: Push Docker Hub
      run: |
        echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
        docker push sambasy/llm-api:latest

    - name: Import dans K3s
      run: |
        docker save sambasy/llm-api -o /tmp/llm-api.tar
        scp -o StrictHostKeyChecking=no /tmp/llm-api.tar ubuntu@192.168.65.45:~/llm-api.tar
        ssh -o StrictHostKeyChecking=no ubuntu@192.168.65.45 "sudo k3s ctr images import ~/llm-api.tar"

    - name: Deploy LLM sur K8s
      run: |
        helm upgrade --install mlops-app ./mlops-chart \
          --set irisModel.image=sambasy/iris-model:latest \
          --set llmApi.image=sambasy/llm-api:latest

  # ── JOB 3 : Deploy sur SageMaker ──
  sagemaker-pipeline:
    runs-on: self-hosted
    needs: iris-pipeline

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Copier mlruns dans workspace
      run: |
        cp -r ~/mlops-project/mlruns $GITHUB_WORKSPACE/mlruns

    - name: Configure AWS credentials
      run: |
        aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws configure set region ca-central-1

    - name: Login ECR
      run: |
        aws ecr get-login-password --region ca-central-1 | \
          docker login --username AWS \
          --password-stdin 961743401926.dkr.ecr.ca-central-1.amazonaws.com

    - name: Build et Push vers ECR (amd64)
      run: |
        docker buildx use amd64builder || docker buildx create --use --name amd64builder
        docker buildx build \
          --platform linux/amd64 \
          --provenance=false \
          --sbom=false \
          -f Dockerfile.sagemaker \
          -t 961743401926.dkr.ecr.ca-central-1.amazonaws.com/iris-model:latest \
          --push \
          .

    - name: Deploy sur SageMaker avec Terraform.
      run: |
        cd terraform-aws
        terraform init
        
        # Importer les ressources existantes si elles existent
        terraform import aws_iam_role.sagemaker_role mlops-sagemaker-role || true
        
        terraform import aws_iam_role_policy_attachment.sagemaker_policy \
          mlops-sagemaker-role/arn:aws:iam::aws:policy/AmazonSageMakerFullAccess || true
        
        terraform import aws_iam_role_policy_attachment.s3_policy \
          mlops-sagemaker-role/arn:aws:iam::aws:policy/AmazonS3FullAccess || true
        
        terraform apply -auto-approve

    - name: Tester l'endpoint SageMaker
      run: |
        echo '{"inputs": [[5.1, 3.5, 1.4, 0.2]]}' > /tmp/request.json
        aws sagemaker-runtime invoke-endpoint \
          --endpoint-name iris-model-endpoint \
          --content-type application/json \
          --body fileb:///tmp/request.json \
          --region ca-central-1 \
          /tmp/output.json
        cat /tmp/output.json
