name: MLOps Pipeline

on:
  push:
    branches: [ main ]
    paths:
      - 'train.py'
      - 'Dockerfile'
      - 'app.py'
      - 'llm_app.py'
      - 'Dockerfile.llm'
      - 'deployment.yml'
      - 'deployment-llm.yml'
      - 'service.yml'
      - 'service-llm.yml'
      - '.github/workflows/mlops-pipeline.yml'

jobs:
  iris-pipeline:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        source ~/mlops-project/mlops-env/bin/activate
        pip install mlflow scikit-learn pandas

    - name: Train model
      run: |
        source ~/mlops-project/mlops-env/bin/activate
        cd $GITHUB_WORKSPACE
        MLFLOW_TRACKING_URI=http://192.168.65.37:5000 \
        MLFLOW_ALLOW_FILE_STORE=true \
        python train.py
    
    - name: Copier mlruns dans workspace
      run: |
        cp -r ~/mlops-project/mlruns $GITHUB_WORKSPACE/mlruns

    - name: Build and Push Iris image
      run: |
        docker build -t sambasy/iris-model:latest .
        echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
        docker push sambasy/iris-model:latest

    - name: Deploy Iris sur Kubernetes
      run: |
        kubectl apply -f deployment.yml
        kubectl apply -f service.yml
        kubectl rollout restart deployment/iris-model

  llm-pipeline:
    runs-on: self-hosted
    needs: iris-pipeline

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Build LLM image
      run: |
        docker build -f Dockerfile.llm -t sambasy/llm-api:latest .

    - name: Push Docker Hub
      run: |
        echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
        docker push sambasy/llm-api:latest

    - name: Import dans K3s
      run: |
        docker save sambasy/llm-api -o /tmp/llm-api.tar
        scp /tmp/llm-api.tar ubuntu@192.168.65.40:~/llm-api.tar
        ssh ubuntu@192.168.65.40 "sudo k3s ctr images import ~/llm-api.tar"

    - name: Deploy LLM sur Kubernetes
      run: |
        kubectl apply -f deployment-llm.yml
        kubectl apply -f service-llm.yml
        kubectl rollout restart deployment/llm-api
